[tool.ruff]
line-length = 90  # Puedes cambiarlo según tu preferencia
target-version = "py312"  # Ajusta según tu versión de Python
select = [
    "ALL"  # Habilita todas las reglas disponibles
]
ignore = [
    "D203",  # Opcional: Evita conflictos entre D203 y D211 en docstrings
    "D213"   # Opcional: Para estilos de docstring consistentes
    
]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"  # Prefiere comillas dobles en docstrings

[tool.ruff.pydocstyle]
convention = "google"  # O "numpy", si prefieres ese estilo

[tool.ruff.mccabe]
max-complexity = 10  # Ajusta según la complejidad permitida en las funciones

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]  # Permite el uso de `assert` en pruebas
